// task_command.sh

python3 taskproducer.py First message.
python3 taskproducer.py Second message..
python3 taskproducer.py Third message...
python3 taskproducer.py Fourth message....
python3 taskproducer.py Fifth message.....
python3 taskproducer.py Sixth message.....
