version: '2'

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"

  consumer:
    image: python:3.7-alpine
    container_name: rabbit_consumer_container
    build: ./rabbitmq-consumer
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure

  producer:
    image: python:3.9-alpine
    container_name: rabbit_producer_container
    build: ./rabbitmq-producer
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure


