version: '2'

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - rabbit-net

  consumer:
    image: python:3
    container_name: rabbit_consumer_container
    build:
      context: ./rabbitmq-consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq-container
    tty: true
    networks:
      - rabbit-net
    restart: on-failure

  producer:
    image: python:3
    container_name: rabbit_producer_container
    build:
      context: ./rabbitmq-producer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq-container
    tty: true
    networks:
      - rabbit-net
    restart: on-failure

networks:
  rabbit-net:
    external: true
    name: rabbit-net

