version: '2'

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"
    #networks:
      #- rabbit-net

  consumer:
    image: python:3.7
    container_name: rabbit_consumer_container
    build:
      context: ./rabbitmq-consumer
      dockerfile: Dockerfile
    command: python3 consumer.py
    depends_on:
      - rabbitmq-container
    tty: true
    #networks:
    #  - rabbit-net
    restart: on-failure

  producer:
    image: python:3.9
    container_name: rabbit_producer_container
    build:
      context: ./rabbitmq-producer
      dockerfile: Dockerfile
    command: python3 producer.py
    depends_on:
      - consumer
    tty: true
    #networks:
      #- rabbit-net
    restart: on-failure

#networks:
  #rabbit-net:
    #external: true
    #name: rabbit-net

