version: '2'

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"

  worker1:
    build: ./task-worker
    command: python3 taskworker.py
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure

  worker2:
    build: ./task-worker
    command: python3 taskworker.py
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure


  tasker:
    build: ./task-producer
    command: python3 taskproducer.py
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure


