version: '2'

services:
  rabbitmq-container:
    image: rabbitmq:3-management
    hostname: rabbitmq-container
    ports:
      - "15672:15672"
      - "5672:5672"

  subscriber1:
    build: ./sub
    command: python3 subscriber.py
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure


  publisher:
    build: ./pub
    command: python3 publisher.py
    depends_on:
      - rabbitmq-container
    tty: true
    restart: on-failure


